### ISSUE TITLE
Improve Workflow

### ISSUE THREAD

**Issue by Andy-Python-Programmer** [Calamity210/Senegal#6]
Improve the workflow to install dart at the start without needing to commit the executable to the repo as it will make the commit history not readable.

**Comment by Calamity210** [comment]
Can this be closed after #7 was merged?

**Comment by Andy-Python-Programmer** [comment]
I think we will need to add the windows-latest workflow too just to double check Senegal runs on all platforms perfectly.

**Comment by Calamity210** [comment]
Closing as https://github.com/Calamity210/Senegal/issues/6#issuecomment-729984314 is unrelated to this issue

**Comment by Andy-Python-Programmer** [comment]
Ah yes lol. My bad

**Comment by Andy-Python-Programmer** [comment]
Just one more thing ^^^^^^^^^^
